// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-cdG16vj8Pbqt5mDEDn-dwcNRAdjZk8',
    appId: '1:459922083838:web:09060b5e45897fb8a5baaf',
    messagingSenderId: '459922083838',
    projectId: 'ecommerce-b9586',
    authDomain: 'ecommerce-b9586.firebaseapp.com',
    storageBucket: 'ecommerce-b9586.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxmTaeiZKzTisY5ZqoLW79DA6ZmzvyDyY',
    appId: '1:459922083838:android:9b5673a1dc143b78a5baaf',
    messagingSenderId: '459922083838',
    projectId: 'ecommerce-b9586',
    storageBucket: 'ecommerce-b9586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmgH_1OcrLhXxfUTDuUoUTYCVAbirAy-Q',
    appId: '1:459922083838:ios:b0de3e9bb8ce3b18a5baaf',
    messagingSenderId: '459922083838',
    projectId: 'ecommerce-b9586',
    storageBucket: 'ecommerce-b9586.firebasestorage.app',
    iosBundleId: 'com.domain.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmgH_1OcrLhXxfUTDuUoUTYCVAbirAy-Q',
    appId: '1:459922083838:ios:b0de3e9bb8ce3b18a5baaf',
    messagingSenderId: '459922083838',
    projectId: 'ecommerce-b9586',
    storageBucket: 'ecommerce-b9586.firebasestorage.app',
    iosBundleId: 'com.domain.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-cdG16vj8Pbqt5mDEDn-dwcNRAdjZk8',
    appId: '1:459922083838:web:72739e981231ce43a5baaf',
    messagingSenderId: '459922083838',
    projectId: 'ecommerce-b9586',
    authDomain: 'ecommerce-b9586.firebaseapp.com',
    storageBucket: 'ecommerce-b9586.firebasestorage.app',
  );
}
